/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import RMI.AdminDTO;

import javax.swing.JButton;
import java.awt.*;

/**
 * @author Assar
 */
public class AdminDashboardGUI extends javax.swing.JFrame {
    
    /**
     * Creates new form VolunteerDashboard
     */
    private AdminDTO adminDTO;
    
    public AdminDashboardGUI() {
        initComponents();
    }
    
    public AdminDashboardGUI(AdminDTO adminDTO) {
        initComponents();
        this.adminDTO = adminDTO;
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        jLabel1 = new javax.swing.JLabel();
        jButtonViewInventory = new javax.swing.JButton();
        jButtonViewSellingItems = new javax.swing.JButton();
        jButtonAdminViewAllAnimals = new javax.swing.JButton();
        jButtonAdminViewAllVolunteeringTasks = new javax.swing.JButton();
        jButtonAdminManageAccount = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Admin Dashboard");
        
        jButtonViewInventory.setText("View Inventory");
        
        jButtonViewSellingItems.setText("View Selling Items");
        
        jButtonAdminViewAllAnimals.setText("View All Animals");
        
        jButtonAdminViewAllVolunteeringTasks.setText("View All Volunteering Tasks");
        
        jButtonAdminManageAccount.setText("Manage Account");
        
        jButtonLogout.setText("Log out");
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonAdminManageAccount)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButtonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonViewInventory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addGap(52, 52, 52))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonAdminViewAllAnimals, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButtonAdminViewAllVolunteeringTasks)
                                                        .addComponent(jButtonViewSellingItems, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(36, 36, 36))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel1)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonViewInventory)
                                        .addComponent(jButtonViewSellingItems))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonAdminViewAllVolunteeringTasks)
                                        .addComponent(jButtonAdminViewAllAnimals))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonLogout)
                                        .addComponent(jButtonAdminManageAccount))
                                .addGap(23, 23, 23))
        );
        
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JButton getjButtonAdminManageAccount() {
        return jButtonAdminManageAccount;
    }
    
    public JButton getjButtonLogout() {
        return jButtonLogout;
    }
    
    public JButton getjButtonAdminViewAllAnimals() {
        return jButtonAdminViewAllAnimals;
    }
    
    public JButton getjButtonAdminViewAllVolunteeringTasks() {
        return jButtonAdminViewAllVolunteeringTasks;
    }
    
    public JButton getjButtonViewInventory() {
        return jButtonViewInventory;
    }
    
    public JButton getjButtonViewSellingItems() {
        return jButtonViewSellingItems;
    }
    
    public AdminDTO getAdminDTO() {
        return adminDTO;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboardGUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdminManageAccount;
    private javax.swing.JButton jButtonAdminViewAllAnimals;
    private javax.swing.JButton jButtonAdminViewAllVolunteeringTasks;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonViewInventory;
    private javax.swing.JButton jButtonViewSellingItems;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
