/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import RMI.EmployeeDTO;

/**
 *
 * @author Shero
 */
public class CaretakerBookDoctorAppointmentGUI extends javax.swing.JFrame {

        /**
         * Creates new form CaretakerBookDoctorAppointment
         */
        EmployeeDTO caretakerDTO;
        EmployeeDTO employeeDTO;
        int animalID;

        public CaretakerBookDoctorAppointmentGUI(EmployeeDTO caretakerDTO) {
                initComponents();
                setLocationRelativeTo(null);
                this.caretakerDTO = caretakerDTO;
        }

        public CaretakerBookDoctorAppointmentGUI(EmployeeDTO employeeDTO, int animalID) {
                initComponents();
                setLocationRelativeTo(null);
                this.employeeDTO = employeeDTO;
                this.animalID = animalID;
        }

        public CaretakerBookDoctorAppointmentGUI() {
                initComponents();
                setLocationRelativeTo(null);
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButtonBackBookDoctorAppointment = new javax.swing.JButton();
                jButtonBookAppointmentCaretakerBookAppointment = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                jComboBoxAppointmentTypeBookAppointment = new javax.swing.JComboBox<>();
                jTextFieldDayBookDoctorAppointment = new javax.swing.JTextField();
                jTextFieldMonthBookDoctorAppointment = new javax.swing.JTextField();
                jTextFieldYearBookDoctorAppointment = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jButtonBackBookDoctorAppointment.setText("Back");

                jButtonBookAppointmentCaretakerBookAppointment.setText("Book Appointment");

                jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabel1.setText("Book Doctor Appointment");

                jLabel2.setText("Date");

                jLabel3.setText("Appointment Type");

                jComboBoxAppointmentTypeBookAppointment
                                .setModel(new javax.swing.DefaultComboBoxModel<>(
                                                new String[] { "Checkup", "Vaccine", "Surgery" }));

                jTextFieldDayBookDoctorAppointment.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextFieldDayBookDoctorAppointmentActionPerformed(evt);
                        }
                });

                jLabel4.setText("Day");

                jLabel5.setText("Month");

                jLabel6.setText("Year");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(76, 76, 76)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(jLabel2,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                55,
                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                .addGap(27, 27, 27)
                                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                                .addComponent(jLabel4)
                                                                                                                                                                                .addGap(32, 32, 32)
                                                                                                                                                                                .addComponent(jLabel5,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                34,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                                                .addComponent(jLabel6,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                34,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                jTextFieldDayBookDoctorAppointment,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                34,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addGap(18, 18, 18)
                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                jTextFieldMonthBookDoctorAppointment,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                36,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                jTextFieldYearBookDoctorAppointment,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                33,
                                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                layout
                                                                                                                                                .createParallelGroup(
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(jLabel1)
                                                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                                                .addComponent(jLabel3)
                                                                                                                                                                .addGap(32, 32, 32)
                                                                                                                                                                .addComponent(
                                                                                                                                                                                jComboBoxAppointmentTypeBookAppointment,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                92,
                                                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addComponent(jButtonBackBookDoctorAppointment,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                73,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(132, 132, 132)
                                                                                                .addComponent(jButtonBookAppointmentCaretakerBookAppointment)))
                                                                .addContainerGap(79, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGap(48, 48, 48)
                                                                .addComponent(jLabel1)
                                                                .addGap(36, 36, 36)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(jComboBoxAppointmentTypeBookAppointment,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(21, 21, 21)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel4)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(jLabel6))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel2)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                .addComponent(jTextFieldDayBookDoctorAppointment,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jTextFieldMonthBookDoctorAppointment,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(jTextFieldYearBookDoctorAppointment,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                29,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButtonBookAppointmentCaretakerBookAppointment)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jButtonBackBookDoctorAppointment)
                                                                .addContainerGap()));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jTextFieldDayBookDoctorAppointmentActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldDayBookDoctorAppointmentActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_jTextFieldDayBookDoctorAppointmentActionPerformed

        public EmployeeDTO getCaretakerDTO() {
                return caretakerDTO;
        }

        public EmployeeDTO getEmployeeDTO() {
                return employeeDTO;
        }

        public int getAnimalID() {
                return animalID;
        }

        public javax.swing.JButton getjButtonBackBookDoctorAppointment() {
                return jButtonBackBookDoctorAppointment;
        }

        public javax.swing.JButton getjButtonBookAppointmentCaretakerBookAppointment() {
                return jButtonBookAppointmentCaretakerBookAppointment;
        }

        public javax.swing.JComboBox<String> getjComboBoxAppointmentTypeBookAppointment() {
                return jComboBoxAppointmentTypeBookAppointment;
        }

        public javax.swing.JTextField getjTextFieldDayBookDoctorAppointment() {
                return jTextFieldDayBookDoctorAppointment;
        }

        public javax.swing.JTextField getjTextFieldMonthBookDoctorAppointment() {
                return jTextFieldMonthBookDoctorAppointment;
        }

        public javax.swing.JTextField getjTextFieldYearBookDoctorAppointment() {
                return jTextFieldYearBookDoctorAppointment;
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(CaretakerBookDoctorAppointmentGUI.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(CaretakerBookDoctorAppointmentGUI.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(CaretakerBookDoctorAppointmentGUI.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(CaretakerBookDoctorAppointmentGUI.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new CaretakerBookDoctorAppointmentGUI().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButtonBackBookDoctorAppointment;
        private javax.swing.JButton jButtonBookAppointmentCaretakerBookAppointment;
        private javax.swing.JComboBox<String> jComboBoxAppointmentTypeBookAppointment;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JTextField jTextFieldDayBookDoctorAppointment;
        private javax.swing.JTextField jTextFieldMonthBookDoctorAppointment;
        private javax.swing.JTextField jTextFieldYearBookDoctorAppointment;
        // End of variables declaration//GEN-END:variables
}