/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

import RMI.EmployeeDTO;

/**
 *
 * @author Shero
 */
public class EmployeeViewAnimalGUI extends javax.swing.JFrame {

    /**
     * Creates new form ViewAnimalGUI
     */

    EmployeeDTO employeeDTO;
    int animalID;

    public EmployeeViewAnimalGUI(EmployeeDTO employeeDTO, int animalID) {
        this.employeeDTO = employeeDTO;
        this.animalID = animalID;
        initComponents();
    }
     
    public EmployeeViewAnimalGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRecordFeedingViewAnimal = new javax.swing.JButton();
        jButtonBookDoctorAppointmentViewAnimal = new javax.swing.JButton();
        jButtonBackViewAnimalGUI = new javax.swing.JButton();
        jTextFieldAnimalNameViewAnimalGUI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAnimalDetailsViewAnimal = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonRecordFeedingViewAnimal.setText("Record Feeding");

        jButtonBookDoctorAppointmentViewAnimal.setText("Book Doctor Appointment");

        jButtonBackViewAnimalGUI.setText("Back");

        jTextFieldAnimalNameViewAnimalGUI.setEditable(false);
        jTextFieldAnimalNameViewAnimalGUI.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTableAnimalDetailsViewAnimal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Animal ID", null},
                {"Animal Name", null},
                {"Animal Type", null},
                {"Animal Breed", null},
                {"Animal Age", null},
                {"Last Feeding", null},
                {"Adopted Status", null},
                {"Sponsored Status", null},
                {"Fostered Status", null},
                {null, null}
            },
            new String [] {
                "Field", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAnimalDetailsViewAnimal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jButtonRecordFeedingViewAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBookDoctorAppointmentViewAnimal)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonBackViewAnimalGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jTextFieldAnimalNameViewAnimalGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTextFieldAnimalNameViewAnimalGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRecordFeedingViewAnimal)
                    .addComponent(jButtonBookDoctorAppointmentViewAnimal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jButtonBackViewAnimalGUI)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getjButtonBackViewAnimalGUI() {
        return jButtonBackViewAnimalGUI;
    }

    public JButton getjButtonBookDoctorAppointmentViewAnimal() {
        return jButtonBookDoctorAppointmentViewAnimal;
    }

    public JButton getjButtonRecordFeedingViewAnimal() {
        return jButtonRecordFeedingViewAnimal;
    }


    public JTable getjTableAnimalDetailsViewAnimal() {
        return jTableAnimalDetailsViewAnimal;
    }

    public JTextField getjTextFieldAnimalNameViewAnimalGUI() {
        return jTextFieldAnimalNameViewAnimalGUI;
    }
    
    public EmployeeDTO getEmployeeDTO() {
        return employeeDTO;
    }

    public int getAnimalID() {
        return animalID;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewAnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewAnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewAnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeViewAnimalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeViewAnimalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackViewAnimalGUI;
    private javax.swing.JButton jButtonBookDoctorAppointmentViewAnimal;
    private javax.swing.JButton jButtonRecordFeedingViewAnimal;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAnimalDetailsViewAnimal;
    private javax.swing.JTextField jTextFieldAnimalNameViewAnimalGUI;
    // End of variables declaration//GEN-END:variables
}
