/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import RMI.SellingItemDTO;
import RMI.UserDTO;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Shero
 */
public class UserPurchaseItemGUI extends javax.swing.JFrame {
    private UserDTO user;
    private SellingItemDTO sellingItemDTO;

    /**
     * Creates new form UserPurchaseItemGUI
     */
    public UserPurchaseItemGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public UserPurchaseItemGUI(UserDTO user, SellingItemDTO sellingItemDTO) {
        initComponents();
        setLocationRelativeTo(null);
        this.user = user;
        this.sellingItemDTO = sellingItemDTO;
    }

    public JButton getjButtonBackUserPurchase() {
        return jButtonBackUserPurchase;
    }

    public JButton getjButtonConfirmPaymentUserPurchase() {
        return jButtonConfirmPaymentUserPurchase;
    }

    public JRadioButton getjRadioButtonCashUserPurchase() {
        return jRadioButtonCashUserPurchase;
    }

    public JRadioButton getjRadioButtonVisaUserPurchase() {
        return jRadioButtonVisaUserPurchase;
    }

    public JSpinner getjSpinnerQuantityUserPurechase() {
        return jSpinnerQuantityUserPurechase;
    }

    public JTable getjTableShopItemsUserShop() {
        return jTableShopItemsUserShop;
    }

    public JTextField getjTextFieldItemNameUserPurchaseItem() {
        return jTextFieldItemNameUserPurchaseItem;
    }

    public UserDTO getUser() {
        return user;
    }
    
    public SellingItemDTO getSellingItemDTO() {
        return sellingItemDTO;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextFieldItemNameUserPurchaseItem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableShopItemsUserShop = new javax.swing.JTable();
        jLabel = new javax.swing.JLabel();
        jSpinnerQuantityUserPurechase = new javax.swing.JSpinner();
        jRadioButtonCashUserPurchase = new javax.swing.JRadioButton();
        jRadioButtonVisaUserPurchase = new javax.swing.JRadioButton();
        jButtonConfirmPaymentUserPurchase = new javax.swing.JButton();
        jButtonBackUserPurchase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldItemNameUserPurchaseItem.setEditable(false);
        jTextFieldItemNameUserPurchaseItem.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jTableShopItemsUserShop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableShopItemsUserShop.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableShopItemsUserShop);

        jLabel.setText("Quantity");

        jSpinnerQuantityUserPurechase.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        buttonGroup1.add(jRadioButtonCashUserPurchase);
        jRadioButtonCashUserPurchase.setText("Cash");

        buttonGroup1.add(jRadioButtonVisaUserPurchase);
        jRadioButtonVisaUserPurchase.setText("Visa");

        jButtonConfirmPaymentUserPurchase.setText("Confirm Payment");

        jButtonBackUserPurchase.setText("Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jRadioButtonCashUserPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jRadioButtonVisaUserPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonBackUserPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jButtonConfirmPaymentUserPurchase)))
                        .addGap(0, 57, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jTextFieldItemNameUserPurchaseItem, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addComponent(jLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jSpinnerQuantityUserPurechase, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(153, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jTextFieldItemNameUserPurchaseItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCashUserPurchase)
                    .addComponent(jRadioButtonVisaUserPurchase))
                .addGap(18, 18, 18)
                .addComponent(jButtonConfirmPaymentUserPurchase)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButtonBackUserPurchase)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel)
                        .addComponent(jSpinnerQuantityUserPurechase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(140, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPurchaseItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPurchaseItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPurchaseItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPurchaseItemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPurchaseItemGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBackUserPurchase;
    private javax.swing.JButton jButtonConfirmPaymentUserPurchase;
    private javax.swing.JLabel jLabel;
    private javax.swing.JRadioButton jRadioButtonCashUserPurchase;
    private javax.swing.JRadioButton jRadioButtonVisaUserPurchase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerQuantityUserPurechase;
    private javax.swing.JTable jTableShopItemsUserShop;
    private javax.swing.JTextField jTextFieldItemNameUserPurchaseItem;
    // End of variables declaration//GEN-END:variables
}
