package GUI;

import RMI.UserDTO;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 * @author pitos
 */
public class UserDashboardGUI extends javax.swing.JFrame {

    /**
     * Creates new form UserDashboard
     */
    private UserDTO userDTO;

    public UserDashboardGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public UserDashboardGUI(UserDTO userDTO) {
        initComponents();
        setLocationRelativeTo(null);
        this.userDTO = userDTO;
        jTextFieldName.setText(userDTO.getName());
    }

    public JButton getJButtonBookShelterVisit() {
        return jButtonBookShelterVisit;
    }

    public JButton getJButtonViewAnimals() {
        return jButtonViewAnimals;
    }

    public JButton getBookShelterVisitButton() {
        return jButtonBookShelterVisit;
    }

    public JButton getSubscribeToTrainingButton() {
        return jButtonSubscribeToTraining;
    }

    public JButton getViewAnimalsButton() {
        return jButtonViewAnimals;
    }

    public JButton getViewBookingsButton() {
        return jButtonViewBookings;
    }

    public JButton getViewShopButton() {
        return jButtonViewShop;
    }

    public JButton getViewTrainingVideoButton() {
        return jButtonViewTrainingVideo;
    }

    public UserDTO getUser() {
        return userDTO;
    }

    public JButton getjButtonUnSubscribeToTraining() {
        return jButtonUnSubscribeToTraining;
    }

    public JButton getjButtonLogOut() {
        return jButtonLogOut;
    }
    
    public JButton getjButtonViewNextNotification() {
        return jButtonViewNextNotification;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonBookShelterVisit = new javax.swing.JButton();
        jButtonViewBookings = new javax.swing.JButton();
        jButtonViewAnimals = new javax.swing.JButton();
        jButtonViewShop = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonViewNextNotification = new javax.swing.JButton();
        jButtonSubscribeToTraining = new javax.swing.JButton();
        jButtonViewTrainingVideo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonUnSubscribeToTraining = new javax.swing.JButton();
        jButtonLogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Welcome");

        jTextFieldName.setEditable(false);
        jTextFieldName.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Shelter");

        jButtonBookShelterVisit.setText("Book Shelter Visit");
        jButtonBookShelterVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookShelterVisitActionPerformed(evt);
            }
        });

        jButtonViewBookings.setText("View Bookings");
        jButtonViewBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewBookingsActionPerformed(evt);
            }
        });

        jButtonViewAnimals.setText("View Animals");
        jButtonViewAnimals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAnimalsActionPerformed(evt);
            }
        });

        jButtonViewShop.setText("View Shop");
        jButtonViewShop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewShopActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Training");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Account");

        jButtonViewNextNotification.setText("View Next Notification");
        jButtonViewNextNotification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewNextNotificationActionPerformed(evt);
            }
        });

        jButtonSubscribeToTraining.setText("Subscribe to Training");
        jButtonSubscribeToTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubscribeToTrainingActionPerformed(evt);
            }
        });

        jButtonViewTrainingVideo.setText("View Training Video");
        jButtonViewTrainingVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewTrainingVideoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("User Dashboard");

        jButtonUnSubscribeToTraining.setText("UnSubscribe from Training");
        jButtonUnSubscribeToTraining.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnSubscribeToTrainingActionPerformed(evt);
            }
        });

        jButtonLogOut.setText("LogOut");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonViewAnimals)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonBookShelterVisit)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSubscribeToTraining)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonUnSubscribeToTraining)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jButtonViewTrainingVideo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonViewNextNotification)
                            .addComponent(jButtonViewBookings))))
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonViewShop)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(323, 323, 323))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonLogOut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBookShelterVisit)
                    .addComponent(jButtonViewBookings))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewAnimals)
                    .addComponent(jButtonViewShop))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonViewNextNotification)
                    .addComponent(jButtonSubscribeToTraining)
                    .addComponent(jButtonUnSubscribeToTraining))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonViewTrainingVideo)
                .addGap(18, 18, 18)
                .addComponent(jButtonLogOut)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookShelterVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookShelterVisitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBookShelterVisitActionPerformed

    private void jButtonViewBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewBookingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewBookingsActionPerformed

    private void jButtonViewAnimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAnimalsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewAnimalsActionPerformed

    private void jButtonViewShopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewShopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewShopActionPerformed

    private void jButtonViewNextNotificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewNextNotificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewNextNotificationActionPerformed

    private void jButtonSubscribeToTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubscribeToTrainingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSubscribeToTrainingActionPerformed

    private void jButtonViewTrainingVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewTrainingVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonViewTrainingVideoActionPerformed

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonUnSubscribeToTrainingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnSubscribeToTrainingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUnSubscribeToTrainingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDashboardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDashboardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBookShelterVisit;
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JButton jButtonSubscribeToTraining;
    private javax.swing.JButton jButtonUnSubscribeToTraining;
    private javax.swing.JButton jButtonViewAnimals;
    private javax.swing.JButton jButtonViewBookings;
    private javax.swing.JButton jButtonViewNextNotification;
    private javax.swing.JButton jButtonViewShop;
    private javax.swing.JButton jButtonViewTrainingVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
